import { FileSearch, Globe2, Shield, Zap, BarChart3, BookOpen } from "lucide-react";

const features = [
  {
    icon: FileSearch,
    title: "PDF Fact-Checking",
    description:
      "Extract statistics, dates, and technical claims. Verify against live web evidence with confidence scoring.",
  },
  {
    icon: Globe2,
    title: "GEO Analytics",
    description:
      "Measure brand visibility across generative AI engines. Benchmark competitors and optimize discoverability.",
  },
  {
    icon: Shield,
    title: "Multi-Source Verification",
    description:
      "Cross-reference Tavily, Brave Search, and Exa results. Detect outdated stats and false claims.",
  },
  {
    icon: Zap,
    title: "Streaming Analysis",
    description:
      "Real-time pipeline updates with elegant loading states and skeleton loaders.",
  },
  {
    icon: BarChart3,
    title: "Research Dashboard",
    description:
      "Bloomberg-style report views with citations, source cards, and correction suggestions.",
  },
  {
    icon: BookOpen,
    title: "Strategy Reports",
    description:
      "3-month GEO strategies and 1-year monetization roadmaps generated by AI.",
  },
];

export function FeaturesGrid() {
  return (
    <section className="border-b border-border py-24">
      <div className="mx-auto max-w-6xl px-6">
        <h2 className="editorial-heading text-3xl text-stone-900">Built for researchers</h2>
        <p className="mt-3 max-w-xl text-stone-600">
          Everything you need to verify documents and optimize AI visibility.
        </p>

        <div className="mt-14 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((f) => {
            const Icon = f.icon;
            return (
              <div
                key={f.title}
                className="group rounded-lg border border-border bg-card p-6 transition-shadow hover:shadow-[0_2px_12px_rgba(0,0,0,0.04)]"
              >
                <Icon className="h-5 w-5 text-stone-500" strokeWidth={1.5} />
                <h3 className="mt-4 text-[15px] font-medium text-stone-900">{f.title}</h3>
                <p className="mt-2 text-[14px] leading-relaxed text-stone-600">
                  {f.description}
                </p>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
